#Dario Simon Franco 74392984J

COMPILER = g++
OBJ = mcp_greedy.o
TAR = 74392984J.tar.gz
mcp: mcp_greedy.cc
	$(COMPILER) mcp_greedy.cc -o mcp_greedy

tar: 
	tar czvf 74392984J.tar.gz mcp_greedy.cc makefile

clean:
	rm -f $(OBJ) $(TAR)